# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gwt < Formula
  desc "Git worktree helper CLI"
  homepage "https://github.com/djw4/gwt"
  version "1.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/djw4/gwt/releases/download/v1.2.1/gwt_1.2.1_darwin_amd64.tar.gz"
      sha256 "34f2544c2f359a8b26d49ba431c05f06201583c06183a9b8caf1064550c86b91"

      define_method(:install) do
        bin.install "gwt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/djw4/gwt/releases/download/v1.2.1/gwt_1.2.1_darwin_arm64.tar.gz"
      sha256 "501fef4846bc2e58f737987a9836b7379d9cce2c014e6480befa40c775db7c0b"

      define_method(:install) do
        bin.install "gwt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/djw4/gwt/releases/download/v1.2.1/gwt_1.2.1_linux_amd64.tar.gz"
      sha256 "44081dc8863356651f43e000b75685c6547e3ad7043f42999a7e4515e0985b9c"
      define_method(:install) do
        bin.install "gwt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/djw4/gwt/releases/download/v1.2.1/gwt_1.2.1_linux_arm64.tar.gz"
      sha256 "48d7303b4cfd2a46d9432d611f771b85709050ebc9a5ea454cb16f9a2a9cb881"
      define_method(:install) do
        bin.install "gwt"
      end
    end
  end

  test do
    system "#{bin}/gwt", "version"
  end
end
